config/routes.rb
Rails.application.routes.draw do
  resources :reminder_dates, except: %i[index]
  resources :reminders
  devise_for :users
  root 'reminders#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
class Reminder < ApplicationRecord
	belongs_to :user
	after_save :reminder
	validates_presence_of :title, :description, :reminder_date

  def reminder
  	ReminderMailer.reminder_mail(self.user, self).deliver		
  end

  def when_to_run
  	reminder_date + 6.hour + 30.minutes
  end

  handle_asynchronously :reminder, :run_at => Proc.new { |i|  i.when_to_run}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :reminder_date
  has_many :reminders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.all
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
  end

  # GET /reminders/new
  def new
    @reminder = current_user.reminders.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = current_user.reminders.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reminder_params
      params.require(:reminder).permit(:title, :description, :reminder_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to 'Reminder', reminders_path %></li>
      <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/reminders/_form.html.erb
<%= form_for(@reminder, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @reminder.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@reminder.errors.count, "error") %> prohibited this reminder from being saved:</h4>

      <ul>
      <% @reminder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
      <%= f.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label :reminder_date, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.datetime_select :reminder_date, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<div class="page-header">
  <%= link_to reminders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @reminder, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing reminder</h1>
</div>

<%= render 'form' %>

app/views/reminders/index.html.erb
<div class="page-header">
  <%= link_to new_reminder_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Reminder
  <% end %>
  <h1>Listing reminders</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Reminder Date</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @reminders.each do |reminder| %>
        <%= content_tag :tr, id: dom_id(reminder), class: dom_class(reminder) do %>
                      <td><%= reminder.title %></td>
                      <td><%= reminder.description %></td>
                      <td><%= reminder.reminder_date %></td>
                    <td><%= link_to 'Show', reminder %></td>
          <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
          <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reminders/new.html.erb
<div class="page-header">
  <%= link_to reminders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New reminder</h1>
</div>

<%= render 'form' %>

app/views/reminders/show.html.erb
<div class="page-header">
  <%= link_to reminders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_reminder_path(@reminder), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show reminder</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @reminder.title %></dd>

  <dt>Description:</dt>
  <dd><%= @reminder.description %></dd>

  <dt>Reminder date:</dt>
  <dd><%= @reminder.reminder_date %></dd>

</dl>